# The African road network

## Data

## Creating a network from a data frame

```{r}
#| warning: false

#Support for simple features, a standardised way to encode spatial vector data
library(sf)
#Data manipulation
library(dplyr)
# An R package for network manipulation and analysis
library(igraph)
# Provides a number of useful functions for working with character strings in R
library(stringr)
```

```{r}
df_nodes <- read.csv("https://raw.githubusercontent.com/rafaelprietocuriel/AfricanUrbanNetwork/main/AfricaNetworkNodes.csv")

df_edges <- read.csv("https://raw.githubusercontent.com/rafaelprietocuriel/AfricanUrbanNetwork/main/AfricaNetworkEdges.csv")
```

```{r}
g_africa <- graph_from_data_frame(d = df_edges,
                                       vertices = df_nodes,
                                       directed = FALSE)
```

```{r}
head(V(g_africa)$name)
```
```{r}
vertex_attr_names(g_africa)
```

```{r}
edge_attr_names(g_africa)
```

### Visualising the African road network as a spatial network

```{r}

V(g_africa)$size <- 0.035*(V(g_africa)$Pop2015/10000)^0.72

plot(g_africa, vertex.size=V(g_africa)$size, edge.arrow.size=.15, edge.arrow.width=.2, edge.curved=0.1, edge.width=1, edge.color ="gray90",
vertex.color="red", vertex.frame.color="black", vertex.frame.width=0.2,
vertex.label=" ", vertex.label.color="black",
vertex.label.cex=.65) 
```


## Network metrics

### Density

```{r}
edge_density(g_africa, loops=FALSE)
```

### Reciprocity

```{r}
reciprocity(g_africa)
```

### Degree

```{r}
# Compute degree of the nodes given by v belonging to graph g_US, in this case the in-degree
deg <- degree(g_africa, v=V(g_africa))

# Produces histogram of the frequency of nodes with a certain in-degree
hist(deg, breaks = 50, main="Histogram of node degree")
```

```{r}
V(g_africa)$agglosName[degree(g_africa)==max(degree(g_africa))]
V(g_africa)$name[degree(g_africa)==max(degree(g_africa))]
```

```{r}
degree(g_africa, v=c("2896"), mode="in")
```

### Distances

```{r}
shortest_paths(g_africa, 
from = V(g_africa)$agglosName=="Cairo",
to = V(g_africa)$agglosName=="Lagos",
weights=NA, #If weights=NULL and the graph has a weight edge attribute, then the weigth attribute is used. If this is NA then no weights are used (even if the graph has a weight attribute)
output = "both") # outputs both path nodes and edges
```

```{r}
diameter(g_africa, directed=TRUE, weights=NA)
```

```{r}
mean_distance(g_africa, directed=TRUE, weights=NA)
```

### Centrality

```{r}
close_centr <- closeness(g_africa, weights=NA) #using unweighted edges
hist(close_centr, breaks = 50, main="Histogram of closeness centrality")
```
```{r}
between_centr <- betweenness(g_africa, v = V(g_africa), directed = TRUE, weights = NA)
hist(between_centr, breaks = 30, main="Histogram of betweenness centrality")
```


### Hubs and authorities

```{r}
hs <- hub_score(g_africa, weights=NULL)$vector #In this case, we use the weighted edges
hist(hs, breaks = 50, main="Histogram of hub score")
```


```{r}
as <- authority_score(g_africa, weights=NULL)$vector
hist(as, breaks = 50, main="Histogram of authority score")
```

```{r}
c = cluster_fast_greedy(g_africa)
plot(c, g_africa, vertex.size=V(g_africa)$size, edge.arrow.size=.15, edge.arrow.width=.2, edge.curved=0.1, edge.width=1, edge.color ="gray90",
vertex.color="red", vertex.frame.color="black", vertex.frame.width=0.2,
vertex.label=" ", vertex.label.color="black",
vertex.label.cex=.65)
```

